### ISSUE TITLE
Cannot find module 'typesafe-actions'

### ISSUE THREAD

**Issue by jeffarese** [piotrwitek/typesafe-actions#30] opened 2018-05-05 11:54 UTC
I'm using **2.0.0-1** and I get the following error: 

`(1,43): Cannot find module 'typesafe-actions'.`

The funny thing is that if I remove the import, save, add it again and save again, it runs without errors until I restart the build process.

This is the file that causes the error: 

```
import { ActionsUnion, buildAction } from 'typesafe-actions';

const INCREMENT_CURRENT_QUESTION = 'INCREMENT_CURRENT_QUESTION';

export const betPublishActions = {
  incrementCurrentQuestion: buildAction(INCREMENT_CURRENT_QUESTION).empty()
};

export type BetPublishActions = ActionsUnion<typeof betPublishActions>;
```
My project is pretty fresh, created with the TS scripts of create-react-app.

My `package.json`: 

```
{
  "name": "tipsterchat-webapp",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "node-sass-chokidar": "^1.2.2",
    "npm-run-all": "^4.1.2",
    "prettier": "^1.12.1",
    "react": "^16.3.2",
    "react-dom": "^16.3.2",
    "react-redux": "^5.0.7",
    "react-scripts-ts": "2.15.1",
    "redux": "^4.0.0",
    "redux-form": "^7.3.0",
    "typesafe-actions": "2.0.0-1"
  },
  "scripts": {
    "build-css": "node-sass-chokidar src/ -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive",
    "start-js": "react-scripts-ts start",
    "start": "npm-run-all -p watch-css start-js",
    "build-js": "react-scripts-ts build",
    "build": "npm-run-all build-css build-js",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  },
  "devDependencies": {
    "@types/jest": "^22.2.3",
    "@types/node": "^8.10.11",
    "@types/react": "^16.3.13",
    "@types/react-dom": "^16.0.5",
    "@types/react-redux": "^5.0.19",
    "@types/redux-form": "^7.2.4",
    "typescript": "^2.8.3"
  }
}
```

The error keeps appearing after editing any other file (even scss) and I have to remove & add the import again.

**Comment by kjr247** [comment] 2018-05-07 14:00
I wonder if this issue is also related this this packages issue. https://github.com/piotrwitek/react-redux-typescript-guide/issues/63

They are both by the author and this issue seems to be the same.

**Comment by piotrwitek** [comment] 2018-05-07 17:16
I could take a look, but I would need a minimal repo with the error so I can investigate it. Otherwise I'm afraid I won't be able to help you.

**Comment by jeffarese** [comment] 2018-05-07 18:48
Here you can find a basic repo that reproduces it:

https://gitlab.com/jeffarese/typesafe-actions-test

If you go to `typesafe-actions-test/src/store/BetPublish/actions.ts`, remove the import, save, add it again an save it again, it will run. But if you edit something else you'll run into the same error again

**Comment by piotrwitek** [comment] 2018-05-08 09:48
Hi @jeffarese,
First of all you had a broken yarn.lock and I couldn't even install deps.
I started with removing yarn.lock and then `yarn install` and everything works fine, and I cannot reproduce the behaviour you are describing.

**Comment by jeffarese** [comment] 2018-05-08 14:55
![image](https://user-images.githubusercontent.com/3155133/39764693-7870b1de-52e0-11e8-9f86-ce6736744430.png)

I just cloned the test repo and did what's shown on the terminal and I got the same results. 

There's my node & yarn versions, if that matters.

**Comment by piotrwitek** [comment] 2018-05-08 16:30
Ah ok now I see it, I needed to stop and start the build process again

**Comment by piotrwitek** [comment] 2018-05-08 17:18
ok I might figured that one out, it sounds unrelated, but please could you try and confirm if below will fix your error @jeffarese 

Open tslint.json and delete this line:
```
25.     "no-unused-variable": [true, "react"],
```

**Comment by piotrwitek** [comment] 2018-05-08 17:19
here is the issue from the boilerplate provider that I found about this issue: https://github.com/wmonk/create-react-app-typescript/issues/250

**Comment by jeffarese** [comment] 2018-05-09 08:27
@piotrwitek thanks, that fixes it! :open_mouth: pretty enexpected behaviour, right?

**Comment by piotrwitek** [comment] 2018-05-09 08:43
Yea, but that's exactly what you get when you're introducing too much abstraction layers, that's why I put this very straightforward boilerplate to cut the abstractions of development workflow to the minimum (unfortunately it's quite outdated, but could be easily bumped to recent versions with some tweaks)  
https://github.com/piotrwitek/react-redux-typescript-webpack-starter

Closing as this is resolved

**Closed by piotrwitek** 2018-05-09 08:43 UTC
